TRUNCATE TABLE sti RESTART identity CASCADE;
TRUNCATE TABLE node RESTART identity CASCADE;

ALTER TABLE sti ADD FOREIGN KEY (forelder) REFERENCES node (node_id) ON DELETE CASCADE;
ALTER TABLE sti ADD FOREIGN KEY (barn) REFERENCES node (node_id) ON DELETE CASCADE;

ALTER TABLE node RENAME COLUMN node_id TO key;