apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: spoogle-db-policy-dev
  namespace: tbd
spec:
  egress:
    - to:
        - ipBlock:
            cidr: 34.88.10.57/32
  podSelector:
    matchLabels:
      db_policy_user: spooglebruker
  policyTypes:
    - Egress