apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spoogle-opprydding-dev
  namespace: tbd
  labels:
    team: tbd
    db_policy_user: spooglebruker
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
  prometheus:
    enabled: true
    path: /metrics
  webproxy: true
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  envFrom:
    - secret: google-sql-spoogle-spoogle-spoogle-opprydding-dev-a4eb479d
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spoogle-opprydding-dev-v1
    - name: KAFKA_RESET_POLICY
      value: latest
    - name: DATABASE_REGION
      value: europe-north1
    - name: DATABASE_INSTANCE
      value: spoogle
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
