apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spoogle
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://spoogle.intern.dev.nav.no
    - https://spoogle.ansatt.dev.nav.no
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  azure:
    sidecar:
      enabled: true
      autoLogin: true
    application:
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "f787f900-6697-440d-a086-d5bb56e26a9c" # gammel hjemmemekka tbd-gruppe
          - id: "c0227409-2085-4eb2-b487-c4ba270986a3" # nais-tbd
      allowAllUsers: false
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        diskAutoresize: true
        tier: db-f1-micro
        name: spoogle
        flags:
          - name: cloudsql.logical_decoding
            value: "true"
          - name: cloudsql.enable_pglogical
            value: "true"
          - name: cloudsql.enable_pgaudit
            value: "true"
          - name: pgaudit.log
            value: "write"
        databases:
          - name: spoogle
            envVarPrefix: DATABASE
            users:
              - name: spoogle-opprydding-dev
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spoogle-v1
    - name: AZURE_VALID_GROUP_IDS
      value: f787f900-6697-440d-a086-d5bb56e26a9c,c0227409-2085-4eb2-b487-c4ba270986a3
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
