apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spoogle
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://spoogle.intern.nav.no
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 24
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-prod
  secureLogs:
    enabled: true
  azure:
    sidecar:
      enabled: true
      autoLogin: true
    application:
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "f787f900-6697-440d-a086-d5bb56e26a9c" # gammel hjemmemekka tbd-gruppe
          - id: "c0227409-2085-4eb2-b487-c4ba270986a3" # nais-tbd
      allowAllUsers: false
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        diskAutoresize: true
        tier: db-custom-64-65536
        databases:
          - name: spoogle
            envVarPrefix: DATABASE
        flags:
          - name: max_connections
            value: "100"
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spoogle-v2
    - name: KAFKA_RESET_POLICY
      value: earliest
    - name: AZURE_VALID_GROUP_ID
      value: "f787f900-6697-440d-a086-d5bb56e26a9c"
