name: Spoogle-opprydding-dev

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile-opprydding-dev'
      - 'spoogle-opprydding-dev/**'
      - 'build.gradle.kts'
      - '.github/workflows/spoogle-opprydding-dev.yml'
      - 'deploy/dev-opprydding.yml'
      - 'deploy/dev-db-policy.yml'
      - '.dockerignore'

jobs:
  build:
    permissions:
      contents: "read"
      id-token: "write"
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21.x'
          cache: 'gradle'
      - name: test and build
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew :spoogle-opprydding-dev:test :spoogle-opprydding-dev:build
      - uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: 'tbd'
          dockerfile: Dockerfile-opprydding-dev
          image_suffix: opprydding-dev
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deployDev:
    name: deploy to dev
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/dev-opprydding.yml,deploy/dev-db-policy.yml
          IMAGE: ${{ needs.build.outputs.image }}
